### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ainola** [csound/plugins#1]
Hello! As the newest csound has moved a lot of functionality over here it would be nice to have a release cut so packagers are on the same page. 

Thanks!

**Comment by jpffitch** [comment]
6.16 is out.  Where are you?
⁣Sent from TypeApp ​

**Comment by vlazzarini** [comment]
We really need a volunteer to maintain the plugins repo. Releases do not need to be made at every Csound release because the plugins would be compatible across versions. But at the moment, we are very stretched and can't take much more.

**Comment by bc-spreedly** [comment]
I'd be interested in maintaining it but I understand any hesitance given that I've not been active enough in the main csound repo. What would maintenance entail? I was under the impression that a good number of opcodes would be shifted into this repository for Csound 7's release. Is the intention for this repo to contain all non-essential opcodes or to contain all the non-popular ones?

**Comment by ainola** [comment]
I'd be interested in maintaining it but I understand any hesitance given that I've not been active enough in the main csound repo. What would maintenance entail? I was under the impression that a good number of opcodes would be shifted into this repository for Csound 7's release. Is the intention for this repo to contain all non-essential opcodes or to contain all the non-popular ones?

**Comment by vlazzarini** [comment]
Maintenance for now means making builds for MacOS and Windows, and releasing binary packages. I think everything should build out of the box with CMake and the relevant dependencies in place, but maybe the latest additions need to be checked. The main issue with this is how to package the dependencies, whether to attempt to use static libs or to use dynamic libs, etc.
In an ideal world we would have a package manager, but that's beyond the scope of this particular repo project.

For the future, once we are fully committed to Csound 7, then it's a matter of seeing if any modifications are needed so that the opcodes are compatible. For that, there'll be help from the people developing the main system.

**Comment by rschutt** [comment]
I will take a stab at building for MacOS (and maybe windows if I get the MacOS build working).

**Comment by rschutt** [comment]
I was able to do a MacOS build, but don't have AbletonLive, so won't be able to provide a complete build.

**Comment by vlazzarini** [comment]
that's great thanks.

**Comment by vlazzarini** [comment]
I have written an installer script for MacOS, which provided that the faust libraries are static-link and the libpng location is correctly set in the file, should produce zip packages for the plugins. FLTK widget opcodes are excluded because they don't work and Ableton link because I don't have that.

**Comment by vlazzarini** [comment]
Version 1.0 released.
https://github.com/csound/plugins/releases/tag/1.0
